# works a bit different than ios_facts. Here, we take some standard output and parse it into a data model

---
- name: PLAY 1 - Gather Interface Statistics with TextFSM templates
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Run show command
      ios_command: # runs a 'show' command
        commands: "show interfaces switchport"
      register: cli_output

    - name: Parse show command output
      set_fact:
        parsed_interfaces: "{{ cli_output.stdout[0] | parse_cli_textfsm('../ntc-templates/templates/cisco_ios_show_interfaces_switchport.textfsm') }}"

    - name: Write parsed output to file
      copy:
        content: "{{ parsed_interfaces | to_nice_yaml }}"
        dest: "./documentation/textfsm/{{ inventory_hostname }}-parsed.yml"

    - name: Create list of access interfaces
      set_fact:
        access_interfaces: "{{ access_interfaces | default([]) + [item.INTERFACE]  }}"
      with_items: "{{ parsed_interfaces }}"
      when: item.ADMIN_MODE == 'static access'

    - name: List access interfaces
      debug:
        msg: "{{ access_interfaces }}"


    - name: Create list of trunk interfaces
      set_fact:
        trunk_interfaces: "{{ trunk_interfaces | default([]) + [item.INTERFACE]  }}"
      with_items: "{{ parsed_interfaces }}"
      when: item.ADMIN_MODE == 'trunk'

    - name: List trunk interfaces
      debug:
        msg: "{{ trunk_interfaces }}"

    - name: Save access interface list to file
      copy:
        content: "{{ access_interfaces | to_nice_yaml }}"
        dest: "./documentation/textfsm/{{ inventory_hostname }}-access.yml"

    - name: Save trunk interface list to file
      copy:
        content: "{{ trunk_interfaces | to_nice_yaml }}"
        dest: "./documentation/textfsm/{{ inventory_hostname }}-trunk.yml"



...
