# ansible-playbook deploy_config.yml --tags build, deploy
# Tag deploy generates and deploys. Tag build only builds config
# Each task has a dedicated template to render a piece of configuration
# Each piece of configuration is dumped to temp folder, and then assembled into the final configuration

---
- name: PLAY 1 - GENERATE DEVICE CONFIGURATION
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Acquire local date
      shell: "date +%Y-%m-%d"
      register: today
      delegate_to: localhost
      run_once: true
      tags: build,deploy

    - name: Acquire localhost time
      shell: "date +%H:%M:%S"
      register: time
      delegate_to: localhost
      run_once: true
      tags: build,deploy

    - name: Generate Intended Configuration
      template:
        src: ../templates/ios/configuration/intended_config.j2
        dest: ../intended_configs/{{ inventory_hostname }}.cfg
      delegate_to: localhost
      tags: build,deploy

    - name: Update Device Documentation
      template:
        src: ../templates/ios/documentation/device_documentation.j2
        dest: ../documentation/{{ inventory_hostname }}.md
      delegate_to: localhost
      tags: build,deploy

    - name: Deploy intended configuration to device
      ios_config:
        src: ../intended_configs/{{ inventory_hostname }}.cfg
        save_when: changed
      tags: deploy
