host_ethernet_interfaces:
  GigabitEthernet0/0:
    type: l3
    description: MANAGEMENT PORT
    ip_address: 10.1.4.11
    subnet_mask: 255.255.255.0
    dot1x: false
  GigabitEthernet0/1:
    type: edge
    description: USER PORT
    dot1x: true
    shutdown: true # specify port shutdown with this key
# we can override default port profile vlan with the key below
    access_vlan: 225
  GigabitEthernet0/2:
    type: edge
    description: USER PORT
    dot1x: true
  GigabitEthernet0/3:
    type: edge
    description: USER PORT
    dot1x: true
  GigabitEthernet1/0:
    type: edge
    description: USER PORT
    dot1x: true
  GigabitEthernet1/1:
    type: edge
    description: USER PORT
    dot1x: true
  GigabitEthernet1/2:
    type: edge
    description: USER PORT
    dot1x: true
# set DHCP snooping trust on trunk port with key below as needed
  GigabitEthernet1/3:
    type: trunk
    description: test
    dot1x: false
    allowed_vlans: 200,201,202,203,204,205,206,207,208,209,900,999
    dhcp_snooping_trust: true

host_vlan_interfaces:
  Vlan204:
    ip_address: 10.0.4.1
    subnet_mask: 255.255.255.0
    # simply delete below if not using a routing protocol
    routing_protocol:
      ospf:
        process_id: 1
        area: 2
        type: point-to-point
    # simply delete below if not using multicast
    pim: sparse-dense-mode
