---
- name: PLAY 1 - Diff Intended Configuration against Running Configuration, and Fix Device if Needed
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:

    - name: Get localhost date 
      shell: "date +%Y-%m-%d"
      register: today
      run_once: true

    - name: Generate diff - Intended vs Running
      ios_config:
        diff_against: intended 
        intended_config: "{{ lookup ('file', './config_backup/{{ today.stdout }}/{{ inventory_hostname }}-backup.cfg') }}"
        diff_ignore_lines:
          - Current configuration .* # ignore lines in running configuration that can dynamically change, but don't affect device, such as configuration size
      register: diffs

    - name: Fix Device if Needed 
      ios_config:
        src: "./templates/snmp_traps.cfg"
      when: diffs != ""
