---
- name: PLAY 1 - Multiple commands to devices
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Push command to device
      ios_config:
        lines:
          - ntp server 1.1.1.1
          - ntp server 1.1.1.2
          - logging host 5.5.5.5

    - name: Push command to interface
      ios_config:
        lines:
          - description I AM A PORT # child commands ran under parent
          - switchport mode access
          - switchport access vlan 79
      parents:
        - interface GigabitEthernet1/0 # denotes the parent subsection

#  We can also run a loop to issue commands to more than one desired interface
    - name: Push commands to more than one interface
      ios_config:
        lines:
          - description I AM A TRUNK PORT
          - ip dhcp snooping trust
        parents: '{{ item }}'
      with_items:
        - GigabitEthernet1/1
        - GigabitEthernet1/2
